databases:
- name: infisical-db
  databaseName: infisical
  user: infisical
  plan: basic-256mb
  diskSizeGB: 5
  region: singapore

envVarGroups:
- name: infisical-shared
  envVars:
  - key: NODE_ENV
    value: production
  # CRITICAL: After deployment, manually set these in Render dashboard:
  # ENCRYPTION_KEY: openssl rand -hex 16 (16 byte hex string)
  # AUTH_SECRET: openssl rand -base64 32 (32 byte base64 string)
  - key: ENCRYPTION_KEY
    sync: false
  - key: AUTH_SECRET
    sync: false
  - key: SITE_URL
    value: http://localhost:8080

services:
- type: web
  name: infisical-backend
  runtime: image
  autoDeploy: true
  plan: standard
  region: singapore
  image:
    url: infisical/infisical:latest-postgres
  healthCheckPath: /api/status
  envVars:
  - fromGroup: infisical-shared
  - key: PORT
    value: 8080
  - key: DB_CONNECTION_URI
    fromDatabase:
      name: infisical-db
      property: connectionString
  - key: REDIS_URL
    fromService:
      name: infisical-redis
      type: redis
      property: connectionString

- type: redis
  name: infisical-redis
  plan: starter
  region: singapore
  ipAllowList: []
