databases:
- name: infisical-db
  databaseName: infisical
  user: infisical
  plan: basic-256mb
  diskSizeGB: 5
  region: singapore

envVarGroups:
- name: infisical-shared
  envVars:
  - key: NODE_ENV
    value: production

services:
- type: web
  name: infisical-backend
  runtime: image
  autoDeploy: true
  plan: starter
  region: singapore
  image:
    url: infisical/infisical:latest-postgres
  healthCheckPath: /api/status
  envVars:
  - fromGroup: infisical-shared
  - key: PORT
    value: 8080
  - key: DATABASE_URL
    fromDatabase:
      name: infisical-db
      property: connectionString
  - key: REDIS_URL
    fromService:
      name: infisical-redis
      type: redis
      property: connectionString

- type: redis
  name: infisical-redis
  plan: starter
  region: singapore
  ipAllowList: []
