services:
  - type: web
    name: infisical-backend
    env: docker
    image:
      url: infisical/infisical:latest-postgres
      # pullPolicy defaults to always for public images on Render
    plan: starter
    autoDeploy: true
    region: singapore
    # Your app listens on 8080 inside the container (was 80:8080 in compose)
    port: 8080
    envVars:
      - key: NODE_ENV
        value: production
      # Use Render-managed Postgres + Redis connection strings
      - key: DATABASE_URL
        fromDatabase:
          name: infisical-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: infisical-redis
          property: connectionString
    # Optional health check path if your app exposes one:
    # healthCheckPath: /health

  - type: redis
    name: infisical-redis
    plan: starter
    ipAllowList: []        # private by default

databases:
  - name: infisical-db
    databaseName: infisical
    user: infisical
    plan: starter